package services

import (
	"fmt"
	"strings"
	"time"

	"github.com/trisfproject/gatherhub/internal/models"
	"gorm.io/gorm"
)

// BroadcastService manages participant groups and bulk message logs
type BroadcastService struct {
	db                  *gorm.DB
	notificationService *NotificationService
	auditLogService     *AuditLogService
}

// NewBroadcastService creates a new BroadcastService instance
func NewBroadcastService(db *gorm.DB, notificationService *NotificationService, auditLogService *AuditLogService) *BroadcastService {
	return &BroadcastService{
		db:                  db,
		notificationService: notificationService,
		auditLogService:     auditLogService,
	}
}

// GetRecipientsQuery formulates the query based on selected group and filters
func (s *BroadcastService) GetRecipientsQuery(eventID uint, group string, city, industrialEstate, companyName string) *gorm.DB {
	q := s.db.Model(&models.Participant{}).Preload("Event").Preload("Driver")

	if eventID > 0 {
		q = q.Where("participants.event_id = ?", eventID)
	}

	// Audience Group Status filter
	switch strings.ToUpper(group) {
	case "VERIFIED":
		q = q.Where("participants.status = ?", models.StatusVerified)
	case "PENDING":
		q = q.Where("participants.status = ?", models.StatusPending)
	case "CHECKED_IN":
		q = q.Where("participants.status = ?", models.StatusCheckedIn)
	}

	// Additional search filters (case-insensitive LIKE matching)
	if city != "" {
		q = q.Where("participants.city ILIKE ?", "%"+city+"%")
	}
	if industrialEstate != "" {
		q = q.Where("participants.industrial_estate ILIKE ?", "%"+industrialEstate+"%")
	}
	if companyName != "" {
		q = q.Where("participants.company_name ILIKE ?", "%"+companyName+"%")
	}

	return q
}

// GetRecipientsCount counts the matching recipients
func (s *BroadcastService) GetRecipientsCount(eventID uint, group string, city, industrialEstate, companyName string) (int, error) {
	var count int64
	err := s.GetRecipientsQuery(eventID, group, city, industrialEstate, companyName).Count(&count).Error
	return int(count), err
}

// GetRecipients fetches all matching participant records
func (s *BroadcastService) GetRecipients(eventID uint, group string, city, industrialEstate, companyName string) ([]models.Participant, error) {
	var participants []models.Participant
	err := s.GetRecipientsQuery(eventID, group, city, industrialEstate, companyName).Find(&participants).Error
	return participants, err
}

// GetAllBroadcasts retrieves all broadcasts, ordered by date descending
func (s *BroadcastService) GetAllBroadcasts() ([]models.Broadcast, error) {
	var broadcasts []models.Broadcast
	err := s.db.Preload("Event").Order("created_at DESC").Find(&broadcasts).Error
	return broadcasts, err
}

// GetBroadcastByID retrieves a single broadcast record by ID
func (s *BroadcastService) GetBroadcastByID(id uint) (*models.Broadcast, error) {
	var broadcast models.Broadcast
	err := s.db.Preload("Event").First(&broadcast, id).Error
	if err != nil {
		return nil, err
	}
	return &broadcast, nil
}

// GetBroadcastLogs retrieves notification logs generated by a specific broadcast
func (s *BroadcastService) GetBroadcastLogs(broadcastID uint) ([]models.NotificationLog, error) {
	var logs []models.NotificationLog
	err := s.db.Where("broadcast_id = ?", broadcastID).Preload("Participant").Order("created_at DESC").Find(&logs).Error
	return logs, err
}

// RenderTemplate replaces placeholders in the message body template
func (s *BroadcastService) RenderTemplate(msgTmpl string, p *models.Participant) string {
	res := msgTmpl
	res = strings.ReplaceAll(res, "{{participant_name}}", p.FullName)
	res = strings.ReplaceAll(res, "{{registration_number}}", p.RegistrationNumber)
	res = strings.ReplaceAll(res, "{{event_title}}", p.Event.Title)

	var driverName, vehiclePlate, meetingPoint, departureTime string
	if p.OwnVehicle && p.VehicleType == "Car" && p.CarpoolCanBring {
		driverName = p.FullName
		vehiclePlate = p.LicensePlate
		meetingPoint = p.TransportMeetingPoint
		departureTime = p.TransportDepartureTime
	} else if p.DriverID != nil && p.Driver != nil {
		driverName = p.Driver.FullName
		vehiclePlate = p.Driver.LicensePlate
		meetingPoint = p.Driver.TransportMeetingPoint
		departureTime = p.Driver.TransportDepartureTime
	}

	if driverName == "" {
		driverName = "–"
	}
	if vehiclePlate == "" {
		vehiclePlate = "–"
	}
	if meetingPoint == "" {
		meetingPoint = "–"
	}
	if departureTime == "" {
		departureTime = "–"
	}

	res = strings.ReplaceAll(res, "{{driver_name}}", driverName)
	res = strings.ReplaceAll(res, "{{vehicle_plate}}", vehiclePlate)
	res = strings.ReplaceAll(res, "{{meeting_point}}", meetingPoint)
	res = strings.ReplaceAll(res, "{{departure_time}}", departureTime)

	return res
}

// CreateBroadcast records the broadcast details, generates messages, and logs delivery
func (s *BroadcastService) CreateBroadcast(eventID uint, title, message string, audienceGroup string, city, industrialEstate, companyName string) (*models.Broadcast, error) {
	participants, err := s.GetRecipients(eventID, audienceGroup, city, industrialEstate, companyName)
	if err != nil {
		return nil, err
	}

	// Resolve Event details to construct audience description
	var eventTitle string
	var event models.Event
	if err := s.db.First(&event, eventID).Error; err == nil {
		eventTitle = event.Title
	}

	// Audience description constructor
	var audParts []string
	switch strings.ToUpper(audienceGroup) {
	case "VERIFIED":
		audParts = append(audParts, "Terverifikasi")
	case "PENDING":
		audParts = append(audParts, "Pending")
	case "CHECKED_IN":
		audParts = append(audParts, "Checked-In")
	default:
		audParts = append(audParts, "Semua Peserta")
	}

	if city != "" {
		audParts = append(audParts, fmt.Sprintf("Kota: %s", city))
	}
	if industrialEstate != "" {
		audParts = append(audParts, fmt.Sprintf("Kawasan: %s", industrialEstate))
	}
	if companyName != "" {
		audParts = append(audParts, fmt.Sprintf("Perusahaan: %s", companyName))
	}
	if eventTitle != "" {
		audParts = append(audParts, fmt.Sprintf("Acara: %s", eventTitle))
	}
	audienceDesc := strings.Join(audParts, " | ")

	broadcast := &models.Broadcast{
		EventID:         eventID,
		Title:           title,
		Message:         message,
		Audience:        audienceDesc,
		TotalRecipients: len(participants),
		CreatedAt:       time.Now(),
	}

	// Create and dispatch mock broadcasts in a single atomic transaction
	err = s.db.Transaction(func(tx *gorm.DB) error {
		if err := tx.Create(broadcast).Error; err != nil {
			return err
		}

		sentCount := 0
		failedCount := 0

		for _, p := range participants {
			renderedBody := s.RenderTemplate(message, &p)

			// Construct notification log
			logEntry := models.NotificationLog{
				ParticipantID: p.ID,
				EventID:       eventID,
				Recipient:     p.Phone,
				Channel:       "WHATSAPP",
				Message:       renderedBody,
				Status:        "SUCCESS", // Mock delivery is automatically marked successful
				BroadcastID:   &broadcast.ID,
				CreatedAt:     time.Now(),
			}

			if err := tx.Create(&logEntry).Error; err != nil {
				failedCount++
			} else {
				sentCount++
			}
		}

		broadcast.SentCount = sentCount
		broadcast.FailedCount = failedCount

		return tx.Save(broadcast).Error
	})

	if err != nil {
		return nil, err
	}

	return broadcast, nil
}
